### PR TITLE
Update to retry-0.7

### PR DESCRIPTION
**Pull request by rjmac**
Upstream has merged the PR which provides retry policies with access to
the retry counter (as well as other things), so the internal fork of the
retry package can go away.  It also allows/requires the retry policies
to run in the user's monad (it provides a higher-rank synonym to operate
in an unspecified monad to ease the transition, but trying to use it ran
into the unsupported land of impredicative types), so `RetrySettings`
now holds a `RetryPolicyM Client`.  That in turn means `Settings.hs`
needs to know that `Client` exists and is a monad, though nothing else.

### CODE REVIEW

**Comment by twittner** [comment]
Thanks. I'll review it shortly.

**Comment by twittner** [comment]
Since we make no use of the monadic context of `RetryPolicyM` I would not want to specialise it to `Client` or some other monad. Could you please check if the branch [`retry-update`](https://github.com/twittner/cql-io/compare/retry-update) works for you?

**Comment by rjmac** [comment]
Interesting.  That's exactly what I tried first, with the exception that I used the `RetryPolicy` alias defined in the package to name the type of `_retryPolicy` instead of inlining the type.  Apparently there's some interaction between type aliases, `RankNTypes`, and `makeLenses` that I wasn't aware of.  Yes, this works.

**Comment by twittner** [comment]
Thanks again. I have merged `retry-update` into `develop`.

**Pull request closed without merging**
